os: Visual Studio 2015
init: []
install: []
build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- mkdir build
- cd build
- cmake -G "Visual Studio 14 2015" .. -DBADE_INFECTORPP2_DIR:PATH="dependencies/Infectorpp" -DBADE_UNITY_BUILD:BOOL=true
- dir
- cmake --build . --target ALL_BUILD --config Release 
- dir
- cd Release
- dir
- cd ..
- cd Win32
- cd Release
- dir
- cd ..
- cd ..


