// Auto-generated build file
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/Assert.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/BitmapImage.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/CommandQueue.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/ConcreteImageManager.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/ConcreteRenderer.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/ConcreteSampler.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/ConcreteShaderOptions.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/PortableBindings.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/PPMLoader.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/QueueExecutor.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/GL3AsyncProxy.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/GL3Bindings.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/GL3RenderQueue.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/GL3State.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/GL3Texture.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/GL3TextureManager.cpp"
#include "C:/Users/Dario/Documents/GitHub/Bade3D/badeSource/gl3/gl_core_3_3.cpp"
